version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    working_directory: "~/dotfiles"
    steps:
      - checkout
      - run: apt-get update -qq && apt-get install -y python curl git vim
      - run: ~/dotfiles/install
